### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by alpweb** [alpweb/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by for-web-an** [comment]
В цьому розділі в 2-4 реченнях описується, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by alpweb** [comment]
Ok
