### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by alpweb** [alpweb/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by for-web-an** [comment]
Відповідно до назви розділу наводимо посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адресу електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by alpweb** [comment]
Ok
